### ISSUE TITLE
Investigate React map apis

### ISSUE THREAD

**Issue by zthh626** [UVic-Environmental-Engineering-Club/usv-ground-station#1]
The main functionality is to view Cadboro Bay, be able to have a component that will have its state updated to the boat's GPS location, and have the functionality to add pins/locations for the route.

https://deck.gl/docs/developer-guide/interactivity
https://github.com/google-map-react/google-map-react

Looking for react packages, above are two that I've been looking at. Feel free to look at more libraries.

**Comment by johnmck95** [comment]
Useful resource: https://www.digitalocean.com/community/tutorials/how-to-integrate-the-google-maps-api-into-react-applications

**Comment by zthh626** [comment]
Using Google Maps API
