### ISSUE TITLE
fix: angleSlider typo

### ISSUE THREAD

**Issue by daehwankim112** [UVic-Environmental-Engineering-Club/usv-ground-station#19]
folder "angleSlider" at usv-ground-station\src\common\controls\components should be "AngleSlider"

If git does not track capitalizing the name of the folder run
`git config core.ignorecase false`

**Comment by philipesclamado** [comment]
typo was not fixed

**Comment by philipesclamado** [comment]
`git config core.ignorecase false` is needed to enable case sensitivity, as said above. This allows git to track changes in the case.
